### ISSUE TITLE
Fix the issue for main.swift

### ISSUE THREAD

**Issue by eurecho** [Appdev-Swift/9373-Swift-FinalAppdevProject-CodeReviewed#4]
There is an error for the function named isContactNumberValid at main. swift. Kindly, review the code and fix the issue. Also follow the naming standards for the function in this class.

**Comment by SollorinJohnMichael** [comment]
On it Mr. Eurecho.

**Comment by SollorinJohnMichael** [comment]
I have already committed to the main branch sir! Since it's now working. You can close now the issue

**Comment by eurecho** [comment]
Okay, thank you will now close the issue
